FROM node:20-alpine

WORKDIR /app

# Copia e instala dependências
COPY package.json package-lock.json ./
RUN npm ci

# Copia o código
COPY . .

# Build da aplicação
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]