"""add status and media_id to analyses

Revision ID: ae3b0a57a4d2
Revises: 9b924e540fe6
Create Date: 2026-03-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae3b0a57a4d2'
down_revision = '9b924e540fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    analysis_status_enum = sa.Enum('pending', 'done', 'failed', name='analysis_status_enum')
    analysis_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('analyses', sa.Column('status', analysis_status_enum, nullable=False, server_default='pending'))
    op.add_column('analyses', sa.Column('media_id', sa.String(length=255), nullable=True, unique=True))

    op.alter_column('analyses', 'ai_score', existing_type=sa.Float(), nullable=True)
    op.alter_column('analyses', 'result', existing_type=sa.Enum('ai_generated', 'human', 'uncertain', name='result_enum'), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'result', existing_type=sa.Enum('ai_generated', 'human', 'uncertain', name='result_enum'), nullable=False)
    op.alter_column('analyses', 'ai_score', existing_type=sa.Float(), nullable=False)

    op.drop_column('analyses', 'media_id')
    op.drop_column('analyses', 'status')

    analysis_status_enum = sa.Enum('pending', 'done', 'failed', name='analysis_status_enum')
    analysis_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
